[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.3.4"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hyuga611/tsumugi"
rust-version = "1.90"

[workspace.dependencies]
tsg-pty = { path = "crates/tsg-pty" }
tsg-term = { path = "crates/tsg-term" }
tsg-lsp = { path = "crates/tsg-lsp" }

anyhow = "1"
thiserror = "2"
