[package]
name = "tsg-mux"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.23.1"
interprocess = "2.4.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tsg-pty = { version = "0.1.1", path = "../tsg-pty" }
tsg-lsp = { version = "0.1.1", path = "../tsg-lsp" }
tsg-term = { version = "0.1.1", path = "../tsg-term" }
regex = "1.13.1"

[target."cfg(unix)".dependencies]
libc = "0.2"

[target."cfg(windows)".dependencies]
widestring = "1"
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Threading",
] }
