[package]
name = "tsg-probe"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
tsg-pty = { version = "0.3.6", path = "../tsg-pty" }
tsg-term = { version = "0.3.6", path = "../tsg-term" }
